#!/bin/sh
echo Starting ufficionline
trap '' 1
LANG=
export LANG
#PERLIO=:raw
unset PERLIO
export PERLIO
PERLLIB=/opt/webmin
export PERLLIB
cd /home/carlo/ProlocoSanpiero/Info
exec '/home/carlo/ProlocoSanpiero/tgenv/bin/gearbox' $* serve --reload  &
